### ISSUE TITLE
[C4GT Community]: Upgrade React Native

### ISSUE THREAD

**Issue by vinayvenu** [SamanvayOrg/shwaas-android#3]
## Description
React Native needs to be updated to the latest version (along with other libraries) so that we can continue deployments to the PlayStore

## Goals
- Upgrade React Native to version 0.74 (or current version, whichever is the latest)
- Upgrade all existing libraries to the highest version possible

### Expected Outcome

The app should behave as it used to before. 

### Implementation Details

The community upgrade helper will be useful - https://react-native-community.github.io/upgrade-helper/?from=0.64.4&to=0.74.2

### Product Name

Shwaas

### Organisation Name

Samanvay

### Domain

Health

### Tech Skills Needed

React Native

### Mentor(s)

@vinayvenu 

### Complexity

Low

### Category

Mobile

**Comment by tayyab-ilyas** [comment]
hi @vinayvenu can you assign this to me ?

**Comment by trishanu-init** [comment]
@vinayvenu Please assign this issue to me.

**Comment by Anish-Guduri** [comment]
Hi @vinayvenu , It would be great  if you assign this  issue to begin my Open source Journey,  I have good amount  of Experience in React Native framework,  one of the example is where I build my final year Project Self Reliant Agriculture Platform completely using React Native ,React JS, Firebase and Python.

**Comment by VedantKhairnar** [comment]
Hello @Anish-Guduri @trishanu-init @tayyab-ilyas 
Pls directly raise the PR.
Thanks.

**Comment by Asp-Codes** [comment]
@vinayvenu i am facing a issue while running the app.

Could you please help me with this.
![Uploading image.png…]()

**Comment by Shaymon-khawas** [comment]
Hi @VedantKhairnar @vinayvenu  i would like to work on this issue. can you give the list of libraries that i need to upgrade to their  latest vesrion?

**Comment by vinayvenu** [comment]
This is done. Closing
